version: "3.9"
services:
  database:
    image: mariadb
    container_name: database_service
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: text_to_sql_DB
      MYSQL_USER: stefano
      MYSQL_PASSWORD: pwd
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./mariadb_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mariadb", "-h", "127.0.0.1", "-P", "3306", "-u", "root", "-prootpassword", "-e", "SELECT 1"]
      interval: 5s
      retries: 10
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "8003:8003"
    volumes:
      - ./backend:/backend
    # depends_on:
    #   - database
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8003/health"]
      interval: 60s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/frontend
    environment:
      - API_BASE_URL=http://backend:8003
    depends_on:
      backend:
        condition: service_healthy
