version: "3.9"
services:
  database:
    image: mariadb
    restart: always
    container_name: database_service
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: text_to_sql_DB
      MARIADB_USER: root
      # MYSQL_PASSWORD: pwd
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./mariadb_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p", "rootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend_service
    ports:
      - "8003:8003"
    volumes:
      - ./backend:/backend
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/frontend
    environment:
      - API_BASE_URL=http://backend:8003
    depends_on:
      - backend
